# Generated by Django 4.0.1 on 2022-01-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('author', models.CharField(max_length=150)),
                ('publish_date', models.DateField()),
                ('update_date', models.DateField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
