# Generated by Django 4.0.1 on 2022-01-07 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0003_person'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='person',
        ),
    ]
