# Generated by Django 4.0.1 on 2022-01-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0004_alter_person_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='author',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='person',
            name='publish_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='update_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
