# Generated by Django 4.0.1 on 2022-01-07 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0005_person_author_person_body_person_image_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blog',
            table='student',
        ),
    ]
