# Generated by Django 4.0.1 on 2022-01-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0007_alter_blog_image_alter_blog_publish_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='BlogName',
            field=models.CharField(default=True, max_length=150),
            preserve_default=False,
        ),
    ]
