# Generated by Django 4.0.1 on 2022-01-18 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0008_blog_blogname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='BlogName',
        ),
    ]
