# Generated by Django 4.0.1 on 2022-01-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0009_remove_blog_blogname'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='BlogName',
            field=models.CharField(default=False, max_length=150),
            preserve_default=False,
        ),
    ]
